<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.work.assistant</groupId>
    <artifactId>work-assistant</artifactId>
    <version>0.0.3</version>
    <name>work-assistant</name>

    <description>工作助手</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <repositories>
        <repository>
            <id>kunlun-public-repository</id>
            <name>Kunlun Repository by Nexus</name>
            <url>https://kunlun.shijicloud.com/nexus/repository/maven-public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>kunlun-public-plugin-repository</id>
            <name>Kunlun Repository by Nexus</name>
            <url>https://kunlun.shijicloud.com/nexus/repository/maven-public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
    <distributionManagement>
        <repository>
            <id>kunlun-release</id>
            <name>Kunlun Release Repository</name>
            <url>https://kunlun.shijicloud.com/nexus/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>kunlun-snapshot</id>
            <name>Kunlun Snapshot Repository</name>
            <url>https://kunlun.shijicloud.com/nexus/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <java.version>21</java.version>
        <jib.version>3.4.2</jib.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>

        <!-- win-sw evn params and version -->
        <!-- https://mvnrepository.com/artifact/com.sun.winsw/winsw?repo=jenkins-releases -->
        <winsw.version>2.9.0</winsw.version>
        <!-- https://mvnrepository.com/artifact/org.jsoup/jsoup -->
        <org.jsoup.version>1.17.2</org.jsoup.version>
        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <lombok.version>1.18.30</lombok.version>
        <!-- https://mvnrepository.com/artifact/com.querydsl/querydsl-jpa -->
        <verson.querydsl>5.0.0</verson.querydsl>
        <!-- https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit -->
        <retrofit.version>2.9.0</retrofit.version>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
        <org.apache.commons.version>1.11.0</org.apache.commons.version>


        <dist.dir>${project.build.directory}/dist</dist.dir>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <compiler-plugin.version>3.12.1</compiler-plugin.version>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
        <surefire-plugin.version>3.2.5</surefire-plugin.version>

        <!-- https://mvnrepository.com/artifact/org.codehaus.mojo/exec-maven-plugin -->
        <exec-maven-plugin.version>3.2.0</exec-maven-plugin.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- JPA jar/plugin dependency -->
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${verson.querydsl}</version>
            <scope>provided</scope>
            <classifier>jakarta</classifier>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>${verson.querydsl}</version>
            <classifier>jakarta</classifier>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-liquibase</artifactId>
        </dependency>

        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>${retrofit.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-jackson</artifactId>
            <version>${retrofit.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-scalars</artifactId>
            <version>${retrofit.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-jaxb</artifactId>
            <version>${retrofit.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>adapter-rxjava2</artifactId>
            <version>${retrofit.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>${org.jsoup.version}</version>
        </dependency>

        <!-- win-sw jar -->
        <dependency>
            <groupId>com.sun.winsw</groupId>
            <artifactId>winsw</artifactId>
            <version>${winsw.version}</version>
            <classifier>bin</classifier>
            <type>exe</type>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <targetPath>${project.build.directory}/config</targetPath>
                <includes>
                    <include>Dockerfile</include>
                </includes>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>application.yml</include>
                </includes>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>*.sql</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <encoding>UTF-8</encoding>
                            <outputDirectory>${project.build.directory}/scripts</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/scripts</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-dist-resources</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${dist.dir}</outputDirectory>
                            <nonFilteredFileExtensions>
                                <nonFilteredFileExtension>exe</nonFilteredFileExtension>
                            </nonFilteredFileExtensions>
                            <resources>
                                <resource>
                                    <directory>src/main/dist</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.sun.winsw</groupId>
                                    <artifactId>winsw</artifactId>
                                    <classifier>bin</classifier>
                                    <type>exe</type>
                                    <destFileName>service.exe</destFileName>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${dist.dir}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>src/main/assembly/assembly.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--    Jib Maven Plugin
                      作用：
                      1. 将 SpringBoot 项目打包为 Docker 镜像
                      2. 自动推送到腾讯云 TCR 镜像仓库
                      3. 无需 Dockerfile
                      4. 无需执行 docker build / docker push

                      执行命令：
                      mvn clean package -DskipTests jib:build

                      执行后流程：
                      Maven编译
                          ↓
                      Jib构建镜像
                          ↓
                      自动Push腾讯云TCR
                     -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib.version}</version>

                <configuration>

                    <!-- JDK21 基础镜像 -->
                    <from>
                        <image>ccr.ccs.tencentyun.com/java-info/eclipse-temurin:21</image>
                    </from>

                    <!-- 腾讯云镜像仓库 -->
                    <to>
                        <!-- 修改为你的实际仓库 -->
                        <image>
                            ccr.ccs.tencentyun.com/work-assistant/${artifactId}:${version}
                        </image>

                        <!-- 腾讯云账号 -->
                        <auth>
                            <username>test</username>
                            <password>test</password>
                        </auth>

                    </to>

                    <container>
                        <ports>
                            <port>8088</port>
                        </ports>
                        <jvmFlags>
                            <jvmFlag>
                                -XX:+UseContainerSupport
                            </jvmFlag>
                            <jvmFlag>
                                -XX:MaxRAMPercentage=75
                            </jvmFlag>
                            <jvmFlag>
                                -Dfile.encoding=UTF-8
                            </jvmFlag>
                            <jvmFlag>
                                -Duser.timezone=Asia/Shanghai
                            </jvmFlag>
                        </jvmFlags>

                        <creationTime>
                            USE_CURRENT_TIMESTAMP
                        </creationTime>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>prod</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <finalName>work-assistant-${project.version}</finalName>
                <resources>
                    <resource>
                        <directory>src/main/resources/external-properties</directory>
                        <targetPath>${project.build.directory}/config</targetPath>
                        <includes>
                            <include>application.properties</include>
                        </includes>
                        <filtering>true</filtering>
                    </resource>
                </resources>
                <plugins>
                    <!-- front end -->
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>${exec-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>exec-npm-install</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>npm</executable>
                                    <arguments>
                                        <argument>install</argument>
                                    </arguments>
                                    <workingDirectory>./frontend</workingDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>exec-npm-run-build</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>npm</executable>
                                    <arguments>
                                        <argument>run</argument>
                                        <argument>build</argument>
                                    </arguments>
                                    <workingDirectory>./frontend</workingDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-resources-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy-dist-resources</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${dist.dir}</outputDirectory>
                                    <nonFilteredFileExtensions>
                                        <nonFilteredFileExtension>exe</nonFilteredFileExtension>
                                    </nonFilteredFileExtensions>
                                    <resources>
                                        <resource>
                                            <directory>src/main/dist</directory>
                                            <filtering>true</filtering>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                            <execution>
                                <id>copy-static</id>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>copy-resources</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>
                                        ${project.build.directory}/classes/META-INF/resources
                                    </outputDirectory>
                                    <overwrite>true</overwrite>
                                    <resources>
                                        <resource>
                                            <!-- vue resource -->
                                            <directory>
                                                ./frontend/dist
                                            </directory>
                                        </resource>
                                    </resources>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
